version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "127.6.0.6:80:80"
  phpfpm:
    build:
      context: .
      dockerfile: docker/phpfpm.dockerfile
    volumes:
      - ./src/app1:/var/www/html/app1
      - ./src/app2:/var/www/html/app2
